apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-api.fullname" . }}
data:
  DB_HOST: {{ .Release.Name }}-postgresql
  {{- with .Values.configmap }}
  {{- toYaml . | nindent 2}}
  {{- end }}